routes:
  - route: "^.+\\.(js|css|svg|ttf|woff|woff2)$"
    #  cache static assets for 20 years since they are fingerprinted
    headers:
      Cache-Control: "max-age=630720000, no-transform, public"
    gzip: true
  - route: "^.+\\.(ico|pdf|jpg|JPG|jpeg|png|PNG|gif|GIF|mp4|mov|mkv)$"
    #  images 1 week for now because content images are not fingerprinted
    # but without gzip
    headers:
      Cache-Control: "max-age=604800, no-transform, public"
    gzip: false
  - route: "^.+\\.(html|xml|json)$"
    # 5 minutes for main content and design like pages and search index
    headers:
      Cache-Control: "max-age=300, no-transform, public"
    gzip: true
  - route: "^sitemap\\.xml$"
    # sitemap
    headers:
      Cache-Control: "max-age=300, no-transform, public"
      Content-Type: "application/xml; charset=utf-8"
    gzip: true
  - route: "^.+\\.xml$"
    # rss
    headers:
      Cache-Control: "max-age=300, no-transform, public"
      Content-Type: "application/rss+xml; charset=utf-8"
    gzip: true
