---
copyright:
  '©Nevercode Ltd | All Rights Reserved | Codemagic is pending trademark
  of Nevercode Ltd.'
pygmentsUseClasses: true
params:
  twitterShareHandle: codemagicio
  facebookAuthorHandle: codemagicio
  appLoginLink: https://codemagic.io/
  defaultFacebookImage: /uploads/2019/01/default-thumb.png
  defaultTwitterImage: /uploads/2019/02/twitter.png
  headerLinkTitle: Documentation
  locale: en_GB
imaging:
  resampleFilter: linear
  quality: 90
outputs:
  home:
    - HTML
    - RSS
    - JSON
buildDrafts: true
defaultContentLanguage: en
disable404: true

mediaTypes:
  video/mp4:
    suffixes:
      - mp4

title: Codemagic Docs
taxonomies:
  category: categories
disableKinds:
  - taxonomy
  - taxonomyTerm
  - section
