---
new_page_extension: md
auto_deploy: false
admin_path: "/enter"
webhook_url: 
sections:
- type: directory
  path: content
  label: Docs
  create: all
  match: "**/*"
  exclude: "/uploads/*"
  templates:
  - documentation-article
upload_dir: content/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:filename:"
build:
  preview_command: "./build.sh"
  publish_command: "./build.sh"
  preview_env:
  - HUGO_ENV=staging
  - HUGO_ENVIRONMENT=staging
  - HUGO_VERSION=0.55.3
  publish_env:
  - HUGO_ENV=production
  - HUGO_ENVIRONMENT=production
  - HUGO_VERSION=0.55.3
  preview_output_directory: dist
  output_directory: dist
  instant_preview_command: hugo server -D -E -F --port 8080 -s site --bind 0.0.0.0
    --renderToDisk --cleanDestinationDir --disableFastRender -d dist
  preview_docker_image: forestryio/build:latest
  mount_path: "/opt/buildhome/repo"
version: 0.55.3
