name: Site Deployment

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: curl --location --remote-name https://github.com/gohugoio/hugo/releases/download/v0.58.3/hugo_0.58.3_Linux-64bit.deb
      - run: sudo dpkg -i hugo_0.58.3_Linux-64bit.deb
      - run: sudo apt-get install -f
      - run: ./deploy.sh
        working-directory: ${{ github.workspace }}

